autoStore/config/routes.rb
Rails.application.routes.draw do
  
  resources :parts
  
  root 'welcome#index'
  

end

autoStore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

autoStore/app/controllers/parts_controller.rb
class PartsController < ApplicationController

  def new 
  end

  def create
    render plain: params[:part].inspect
  end
  
end

autoStore/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

autoStore/app/helpers/application_helper.rb
module ApplicationHelper
end

autoStore/app/helpers/parts_helper.rb
module PartsHelper
end

autoStore/app/helpers/welcome_helper.rb
module WelcomeHelper
end

autoStore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutoStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

autoStore/app/views/parts/new.html.erb
<h1>New Part</h1>
  <%= form_for :part, url: part_path do |f| %>
  <p>
    <%= f.label :serialNumber %><br>
    <%= f.text_field :serialNumber %>
  </p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>

  <p>
    <%= f.label :partType %><br>
    <%= f.text_area :partType %>
  </p>

  <p>
    <%= f.label :vehicleID %><br>
    <%= f.text_area :vehicleID %>
  </p>

  <p>
    <%= f.label :weight %><br>
    <%= f.text_area :weight %>
  </p>

  <p>
    <%= f.label :shippingCost %><br>
    <%= f.text_area :shippingCost %>
  </p>

  <p>
    <%= f.label :dimensions %><br>
    <%= f.text_area :dimensions %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_area : %>
  </p>
    
  <p>
    <%= f.submit %>
  </p>
<% end %>

autoStore/app/views/welcome/index.html.erb
<h1>Welcome to Parts Co.</h1>